# Generated by Django 5.1.4 on 2026-05-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
