# Generated by Django 5.1.4 on 2026-05-13 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('foundation', 'Foundation'), ('column', 'Column'), ('beam', 'Beam'), ('solid_slab', 'Solid Slab'), ('ribbed_slab', 'Ribbed Slab'), ('wall', 'Wall')], max_length=50)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('count', models.IntegerField(default=1, help_text='Number of identical elements')),
                ('dimensions', models.JSONField(default=dict, help_text='Dimensions as key-value pairs in meters')),
                ('concrete_grade', models.CharField(blank=True, default='C30', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='projects.floor')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('concrete', 'Concrete'), ('rebar', 'Rebar'), ('formwork', 'Formwork')], max_length=50)),
                ('unit', models.CharField(choices=[('m3', 'Cubic Meter'), ('kg', 'Kilogram'), ('m2', 'Square Meter'), ('ton', 'Ton')], max_length=10)),
                ('value', models.FloatField(default=0)),
                ('spec_reference', models.CharField(blank=True, max_length=255)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='quantities.element')),
            ],
        ),
    ]
