# Generated by Django 5.1.4 on 2026-05-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='element_type',
            field=models.CharField(choices=[('foundation', 'Foundation'), ('column', 'Column'), ('beam', 'Beam'), ('solid_slab', 'Solid Slab'), ('ribbed_slab', 'Ribbed Slab'), ('steel_beam', 'Steel Beam (AISC)'), ('steel_column', 'Steel Column (AISC)'), ('steel_connection', 'Steel Connection'), ('retaining_wall', 'Retaining Wall'), ('stairs', 'Stairs')], max_length=50),
        ),
        migrations.AlterField(
            model_name='materialquantity',
            name='material_type',
            field=models.CharField(choices=[('concrete', 'Concrete'), ('rebar', 'Rebar'), ('formwork', 'Formwork'), ('steel_beam', 'Steel Beam'), ('steel_column', 'Steel Column'), ('bolts', 'Bolts'), ('plate', 'Plate'), ('weld', 'Weld')], max_length=50),
        ),
        migrations.AlterField(
            model_name='materialquantity',
            name='unit',
            field=models.CharField(choices=[('m3', 'Cubic Meter'), ('kg', 'Kilogram'), ('m2', 'Square Meter'), ('ton', 'Ton'), ('m', 'Meter')], max_length=10),
        ),
    ]
