# Generated by Django 5.1.4 on 2026-05-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantities', '0002_alter_element_element_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='element_type',
            field=models.CharField(choices=[('foundation', 'Foundation'), ('column', 'Column'), ('beam', 'Beam'), ('solid_slab', 'Solid Slab'), ('ribbed_slab', 'Ribbed Slab'), ('steel_beam', 'Steel Beam (AISC)'), ('steel_column', 'Steel Column (AISC)'), ('steel_connection', 'Steel Connection'), ('retaining_wall', 'Retaining Wall'), ('stairs', 'Stairs'), ('blockwork', 'Blockwork'), ('brickwork', 'Brickwork'), ('tiling', 'Tiling'), ('painting', 'Painting'), ('waterproofing', 'Waterproofing'), ('insulation', 'Insulation'), ('earthwork', 'Earthwork')], max_length=50),
        ),
        migrations.AlterField(
            model_name='materialquantity',
            name='material_type',
            field=models.CharField(choices=[('concrete', 'Concrete'), ('rebar', 'Rebar'), ('formwork', 'Formwork'), ('steel_beam', 'Steel Beam'), ('steel_column', 'Steel Column'), ('bolts', 'Bolts'), ('plate', 'Plate'), ('weld', 'Weld'), ('blocks', 'Blocks'), ('bricks', 'Bricks'), ('mortar', 'Mortar'), ('plaster', 'Plaster'), ('cement', 'Cement'), ('sand', 'Sand'), ('tiles', 'Tiles'), ('adhesive', 'Adhesive'), ('grout', 'Grout'), ('paint', 'Paint'), ('primer', 'Primer'), ('waterproofing', 'Waterproofing'), ('insulation', 'Insulation'), ('insulation_weight', 'Insulation Weight'), ('excavation', 'Excavation'), ('backfill', 'Backfill'), ('haul', 'Haul')], max_length=50),
        ),
    ]
