# Generated by Django 5.1.4 on 2026-05-15 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_user'),
        ('quantities', '0003_alter_element_element_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure_elements', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='element',
            name='element_type',
            field=models.CharField(choices=[('foundation', 'Foundation'), ('column', 'Column'), ('beam', 'Beam'), ('solid_slab', 'Solid Slab'), ('ribbed_slab', 'Ribbed Slab'), ('steel_beam', 'Steel Beam (AISC)'), ('steel_column', 'Steel Column (AISC)'), ('steel_connection', 'Steel Connection'), ('retaining_wall', 'Retaining Wall'), ('stairs', 'Stairs'), ('blockwork', 'Blockwork'), ('brickwork', 'Brickwork'), ('tiling', 'Tiling'), ('painting', 'Painting'), ('waterproofing', 'Waterproofing'), ('insulation', 'Insulation'), ('earthwork', 'Earthwork'), ('road_pavement', 'Road Pavement'), ('water_pipe', 'Water Supply Pipe'), ('sewage_pipe', 'Sewage Pipe'), ('manhole', 'Manhole'), ('sidewalk', 'Sidewalk'), ('curb', 'Curb / Road Barrier'), ('storm_drainage', 'Storm Drainage'), ('water_tank', 'Water Tank'), ('street_lighting', 'Street Lighting')], max_length=50),
        ),
        migrations.AlterField(
            model_name='element',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='projects.floor'),
        ),
        migrations.AlterField(
            model_name='materialquantity',
            name='material_type',
            field=models.CharField(choices=[('concrete', 'Concrete'), ('rebar', 'Rebar'), ('formwork', 'Formwork'), ('steel_beam', 'Steel Beam'), ('steel_column', 'Steel Column'), ('bolts', 'Bolts'), ('plate', 'Plate'), ('weld', 'Weld'), ('blocks', 'Blocks'), ('bricks', 'Bricks'), ('mortar', 'Mortar'), ('plaster', 'Plaster'), ('cement', 'Cement'), ('sand', 'Sand'), ('tiles', 'Tiles'), ('adhesive', 'Adhesive'), ('grout', 'Grout'), ('paint', 'Paint'), ('primer', 'Primer'), ('waterproofing', 'Waterproofing'), ('insulation', 'Insulation'), ('insulation_weight', 'Insulation Weight'), ('excavation', 'Excavation'), ('backfill', 'Backfill'), ('haul', 'Haul'), ('subbase', 'Subbase'), ('base_course', 'Base Course'), ('asphalt', 'Asphalt Concrete'), ('prime_coat', 'Prime Coat'), ('tack_coat', 'Tack Coat'), ('bedding_sand', 'Bedding Sand'), ('pipe_di', 'Ductile Iron Pipe'), ('pipe_pvc', 'PVC Pipe'), ('pipe_hdpe', 'HDPE Pipe'), ('pipe_concrete', 'Concrete Pipe'), ('frame_cover', 'Frame & Cover'), ('pavement', 'Pavement'), ('pole', 'Lighting Pole'), ('luminaire', 'Luminaire'), ('cable', 'Cable')], max_length=50),
        ),
    ]
