# Generated by Django 5.1.4 on 2026-05-14 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('quantities', '0003_alter_element_element_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.CharField(max_length=100)),
                ('unit', models.CharField(help_text='day, m2, m3, ton', max_length=20)),
                ('rate', models.FloatField(help_text='Rate in EGP per unit')),
                ('crew_size', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CostEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Estimate', max_length=255)),
                ('markup_percent', models.FloatField(default=15, help_text='Overhead & profit %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_estimates', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='CostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('unit_price', models.FloatField(default=0)),
                ('total_cost', models.FloatField(default=0)),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quantities.element')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='costing.costestimate')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=10)),
                ('unit_price', models.FloatField(help_text='Price per unit in EGP')),
                ('category', models.CharField(blank=True, help_text='e.g. concrete, rebar, masonry', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('material_type', 'unit')},
            },
        ),
    ]
