# Generated by Django 5.1.4 on 2026-05-14 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('activity_type', models.CharField(choices=[('earthwork', 'Earthwork'), ('foundation', 'Foundation'), ('structure', 'Structure'), ('masonry', 'Masonry'), ('finishing', 'Finishing'), ('insulation', 'Insulation'), ('mep', 'MEP'), ('roofing', 'Roofing'), ('other', 'Other')], default='structure', max_length=50)),
                ('duration_days', models.IntegerField(default=1)),
                ('quantity', models.FloatField(default=0, help_text='Quantity of work')),
                ('unit', models.CharField(blank=True, help_text='Unit of quantity', max_length=20)),
                ('productivity_rate', models.FloatField(default=0, help_text='Quantity per day')),
                ('crew_size', models.IntegerField(default=1)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_end', models.DateField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('early_start', models.IntegerField(default=0)),
                ('early_finish', models.IntegerField(default=0)),
                ('late_start', models.IntegerField(default=0)),
                ('late_finish', models.IntegerField(default=0)),
                ('total_float', models.IntegerField(default=0)),
                ('is_critical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('FS', 'Finish-to-Start'), ('SS', 'Start-to-Start'), ('FF', 'Finish-to-Finish'), ('SF', 'Start-to-Finish')], default='FS', max_length=2)),
                ('lag_days', models.IntegerField(default=0)),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_deps', to='scheduling.activity')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_deps', to='scheduling.activity')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('labor', 'Labor'), ('equipment', 'Equipment'), ('material', 'Material')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.FloatField(default=1)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='scheduling.activity')),
            ],
        ),
    ]
